# Generated by Django 5.1.2 on 2024-10-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=40)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
